import { sql } from "drizzle-orm";
import { getDb } from "@/db";

let bootstrapPromise: Promise<void> | null = null;

export function ensureResearchSchema() {
  if (!bootstrapPromise) bootstrapPromise = runBootstrap();
  return bootstrapPromise;
}

async function runBootstrap() {
  const db = getDb();
  if (!db) return;
  for (const statement of statements) {
    await db.execute(sql.raw(statement));
  }
}

const statements = [
  `DO $$ BEGIN CREATE TYPE story_status AS ENUM ('candidate', 'researching', 'ready', 'rejected', 'published'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN CREATE TYPE recommendation_status AS ENUM ('recommended', 'developing', 'angle_requested', 'investigate_further', 'dismissed', 'dossier_ready'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN CREATE TYPE cluster_status AS ENUM ('candidate', 'merged', 'rejected', 'researching', 'recommended', 'dossier_ready'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN CREATE TYPE research_cycle_status AS ENUM ('queued', 'running', 'completed', 'failed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN CREATE TYPE candidate_status AS ENUM ('active', 'duplicate', 'rejected', 'researching', 'recommended', 'dossier_ready'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN CREATE TYPE investigation_status AS ENUM ('active', 'downgraded', 'ready_for_dossier'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `CREATE TABLE IF NOT EXISTS beats (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug text NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    query_seeds jsonb NOT NULL DEFAULT '[]'::jsonb,
    cadence_weight integer NOT NULL DEFAULT 1,
    active boolean NOT NULL DEFAULT true,
    last_scheduled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS beats_slug_idx ON beats(slug)`,
  `CREATE TABLE IF NOT EXISTS research_cycles (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    beat_id uuid REFERENCES beats(id) ON DELETE SET NULL,
    status research_cycle_status NOT NULL DEFAULT 'queued',
    current_stage text NOT NULL DEFAULT 'discovery',
    stage_state jsonb NOT NULL DEFAULT '{}'::jsonb,
    scheduled_for timestamp with time zone NOT NULL DEFAULT now(),
    locked_at timestamp with time zone,
    completed_at timestamp with time zone,
    error text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS stories (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    beat_id uuid REFERENCES beats(id) ON DELETE SET NULL,
    working_title text NOT NULL,
    category text NOT NULL,
    summary text NOT NULL,
    story_text text,
    event_date text,
    location text,
    status story_status NOT NULL DEFAULT 'candidate',
    interest_score integer NOT NULL DEFAULT 0,
    source_score integer NOT NULL DEFAULT 0,
    competition_score integer NOT NULL DEFAULT 0,
    confidence_score integer NOT NULL DEFAULT 0,
    chronology jsonb DEFAULT '[]'::jsonb,
    key_facts jsonb DEFAULT '[]'::jsonb,
    conflicts jsonb DEFAULT '[]'::jsonb,
    titles jsonb DEFAULT '[]'::jsonb,
    outline jsonb DEFAULT '[]'::jsonb,
    premise text,
    narrative_hook text,
    why_overlooked text,
    originality_assessment text,
    unresolved_risks jsonb DEFAULT '[]'::jsonb,
    research_completeness integer NOT NULL DEFAULT 0,
    recommended_next_action text,
    claim_citations jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `ALTER TABLE stories ADD COLUMN IF NOT EXISTS beat_id uuid REFERENCES beats(id) ON DELETE SET NULL`,
  `ALTER TABLE stories ADD COLUMN IF NOT EXISTS story_text text`,
  `ALTER TABLE stories ADD COLUMN IF NOT EXISTS premise text`,
  `ALTER TABLE stories ADD COLUMN IF NOT EXISTS narrative_hook text`,
  `ALTER TABLE stories ADD COLUMN IF NOT EXISTS why_overlooked text`,
  `ALTER TABLE stories ADD COLUMN IF NOT EXISTS originality_assessment text`,
  `ALTER TABLE stories ADD COLUMN IF NOT EXISTS unresolved_risks jsonb DEFAULT '[]'::jsonb`,
  `ALTER TABLE stories ADD COLUMN IF NOT EXISTS research_completeness integer NOT NULL DEFAULT 0`,
  `ALTER TABLE stories ADD COLUMN IF NOT EXISTS recommended_next_action text`,
  `ALTER TABLE stories ADD COLUMN IF NOT EXISTS claim_citations jsonb DEFAULT '[]'::jsonb`,
  `CREATE TABLE IF NOT EXISTS sources (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    story_id uuid NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    url text NOT NULL,
    title text NOT NULL,
    publisher text,
    publication_date text,
    source_type text NOT NULL,
    archive_identifier text,
    excerpt text,
    primary_source boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS research_runs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    cycle_id uuid REFERENCES research_cycles(id) ON DELETE SET NULL,
    beat_id uuid REFERENCES beats(id) ON DELETE SET NULL,
    status text NOT NULL,
    query_set jsonb DEFAULT '[]'::jsonb,
    candidates_found integer NOT NULL DEFAULT 0,
    stories_saved integer NOT NULL DEFAULT 0,
    error text,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    completed_at timestamp with time zone
  )`,
  `ALTER TABLE research_runs ADD COLUMN IF NOT EXISTS cycle_id uuid REFERENCES research_cycles(id) ON DELETE SET NULL`,
  `ALTER TABLE research_runs ADD COLUMN IF NOT EXISTS beat_id uuid REFERENCES beats(id) ON DELETE SET NULL`,
  `CREATE TABLE IF NOT EXISTS archive_records (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    cycle_id uuid REFERENCES research_cycles(id) ON DELETE SET NULL,
    beat_id uuid REFERENCES beats(id) ON DELETE SET NULL,
    run_id uuid REFERENCES research_runs(id) ON DELETE SET NULL,
    external_id text NOT NULL,
    source text NOT NULL,
    url text NOT NULL,
    title text NOT NULL,
    record_date text,
    location text,
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `ALTER TABLE archive_records ADD COLUMN IF NOT EXISTS cycle_id uuid REFERENCES research_cycles(id) ON DELETE SET NULL`,
  `ALTER TABLE archive_records ADD COLUMN IF NOT EXISTS beat_id uuid REFERENCES beats(id) ON DELETE SET NULL`,
  `CREATE TABLE IF NOT EXISTS research_stage_budgets (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    cycle_id uuid NOT NULL REFERENCES research_cycles(id) ON DELETE CASCADE,
    beat_id uuid REFERENCES beats(id) ON DELETE SET NULL,
    stage text NOT NULL,
    max_records integer NOT NULL DEFAULT 0,
    max_searches integer NOT NULL DEFAULT 0,
    max_model_calls integer NOT NULL DEFAULT 0,
    used_records integer NOT NULL DEFAULT 0,
    used_searches integer NOT NULL DEFAULT 0,
    used_model_calls integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS research_stage_budgets_cycle_stage_idx ON research_stage_budgets(cycle_id, stage)`,
  `CREATE TABLE IF NOT EXISTS candidate_funnel_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    cycle_id uuid NOT NULL REFERENCES research_cycles(id) ON DELETE CASCADE,
    beat_id uuid REFERENCES beats(id) ON DELETE SET NULL,
    archive_record_id uuid REFERENCES archive_records(id) ON DELETE SET NULL,
    external_id text NOT NULL,
    title text NOT NULL,
    hypothesis text NOT NULL,
    normalized_key text NOT NULL,
    status candidate_status NOT NULL DEFAULT 'active',
    rejection_code text,
    rejection_reason text,
    duplicate_of text,
    scores jsonb NOT NULL DEFAULT '{}'::jsonb,
    evidence_source_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS candidate_funnel_cycle_idx ON candidate_funnel_items(cycle_id)`,
  `CREATE INDEX IF NOT EXISTS candidate_funnel_key_idx ON candidate_funnel_items(normalized_key)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS candidate_funnel_cycle_external_idx ON candidate_funnel_items(cycle_id, external_id)`,
  `CREATE TABLE IF NOT EXISTS research_investigations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    cycle_id uuid NOT NULL REFERENCES research_cycles(id) ON DELETE CASCADE,
    beat_id uuid REFERENCES beats(id) ON DELETE SET NULL,
    candidate_id uuid NOT NULL REFERENCES candidate_funnel_items(id) ON DELETE CASCADE,
    status investigation_status NOT NULL DEFAULT 'active',
    working_title text NOT NULL,
    premise text NOT NULL,
    research_questions jsonb NOT NULL DEFAULT '[]'::jsonb,
    follow_up_queries jsonb NOT NULL DEFAULT '[]'::jsonb,
    originality_signals jsonb NOT NULL DEFAULT '[]'::jsonb,
    evidence_depth integer NOT NULL DEFAULT 0,
    source_independence jsonb NOT NULL DEFAULT '[]'::jsonb,
    claim_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
    readiness_score integer NOT NULL DEFAULT 0,
    downgrade_reason text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS research_investigations_candidate_idx ON research_investigations(candidate_id)`,
  `CREATE INDEX IF NOT EXISTS research_investigations_cycle_idx ON research_investigations(cycle_id)`,
  `ALTER TABLE research_investigations ADD COLUMN IF NOT EXISTS claim_evidence jsonb NOT NULL DEFAULT '[]'::jsonb`,
  `ALTER TABLE research_investigations ADD COLUMN IF NOT EXISTS readiness_score integer NOT NULL DEFAULT 0`,
  `CREATE TABLE IF NOT EXISTS story_clusters (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    cycle_id uuid REFERENCES research_cycles(id) ON DELETE SET NULL,
    beat_id uuid REFERENCES beats(id) ON DELETE SET NULL,
    run_id uuid REFERENCES research_runs(id) ON DELETE SET NULL,
    status cluster_status NOT NULL DEFAULT 'candidate',
    label text NOT NULL,
    hypothesis text NOT NULL,
    merge_key text NOT NULL,
    record_ids jsonb DEFAULT '[]'::jsonb,
    rejection_reason text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `ALTER TABLE story_clusters ADD COLUMN IF NOT EXISTS cycle_id uuid REFERENCES research_cycles(id) ON DELETE SET NULL`,
  `ALTER TABLE story_clusters ADD COLUMN IF NOT EXISTS beat_id uuid REFERENCES beats(id) ON DELETE SET NULL`,
  `CREATE TABLE IF NOT EXISTS editorial_recommendations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    cycle_id uuid REFERENCES research_cycles(id) ON DELETE SET NULL,
    beat_id uuid REFERENCES beats(id) ON DELETE SET NULL,
    run_id uuid REFERENCES research_runs(id) ON DELETE SET NULL,
    cluster_id uuid REFERENCES story_clusters(id) ON DELETE SET NULL,
    story_id uuid REFERENCES stories(id) ON DELETE SET NULL,
    status recommendation_status NOT NULL DEFAULT 'recommended',
    working_title text NOT NULL,
    premise text NOT NULL,
    narrative_hook text NOT NULL,
    why_overlooked text NOT NULL,
    strongest_evidence jsonb DEFAULT '[]'::jsonb,
    originality_assessment text NOT NULL,
    unresolved_risks jsonb DEFAULT '[]'::jsonb,
    confidence integer NOT NULL DEFAULT 0,
    research_completeness integer NOT NULL DEFAULT 0,
    recommended_next_action text NOT NULL,
    scores jsonb DEFAULT '{"narrativeTension":0,"sourceStrength":0,"originality":0,"humanInterest":0,"historicalConsequence":0,"researchability":0}'::jsonb,
    source_ids jsonb DEFAULT '[]'::jsonb,
    follow_up_queries jsonb DEFAULT '[]'::jsonb,
    downgrade_reason text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `ALTER TABLE editorial_recommendations ADD COLUMN IF NOT EXISTS cycle_id uuid REFERENCES research_cycles(id) ON DELETE SET NULL`,
  `ALTER TABLE editorial_recommendations ADD COLUMN IF NOT EXISTS beat_id uuid REFERENCES beats(id) ON DELETE SET NULL`,
  `CREATE TABLE IF NOT EXISTS research_activity (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    cycle_id uuid REFERENCES research_cycles(id) ON DELETE SET NULL,
    beat_id uuid REFERENCES beats(id) ON DELETE SET NULL,
    run_id uuid REFERENCES research_runs(id) ON DELETE SET NULL,
    recommendation_id uuid REFERENCES editorial_recommendations(id) ON DELETE SET NULL,
    kind text NOT NULL,
    title text NOT NULL,
    detail text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `ALTER TABLE research_activity ADD COLUMN IF NOT EXISTS cycle_id uuid REFERENCES research_cycles(id) ON DELETE SET NULL`,
  `ALTER TABLE research_activity ADD COLUMN IF NOT EXISTS beat_id uuid REFERENCES beats(id) ON DELETE SET NULL`,
  `CREATE TABLE IF NOT EXISTS research_settings (
    key text PRIMARY KEY,
    value jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamp with time zone NOT NULL DEFAULT now()
  )`,
  `INSERT INTO beats (id, slug, name, description, query_seeds, cadence_weight)
   VALUES
    ('11111111-1111-4111-8111-111111111111', 'forgotten-scandals', 'Forgotten Scandals', 'Fraud, imposture, inheritance disputes, religious scandals, and public controversies with strong narrative tension.', '["historical fraud scandal","disputed inheritance court","religious scandal trial","impostor testimony"]'::jsonb, 3),
    ('22222222-2222-4222-8222-222222222222', 'disasters-and-inquests', 'Disasters and Inquests', 'Industrial, maritime, medical, and civic disasters where inquiry records can reveal accountability and human stakes.', '["industrial disaster inquiry","maritime disaster survivors","medical mystery historical case","inquest testimony"]'::jsonb, 3),
    ('33333333-3333-4333-8333-333333333333', 'power-and-institutions', 'Power and Institutions', 'Government blunders, institutional failures, and public decisions with consequences beyond routine minutes.', '["government blunder investigation","public inquiry testimony","institutional failure historical case"]'::jsonb, 2),
    ('44444444-4444-4444-8444-444444444444', 'strange-local-histories', 'Strange Local Histories', 'Little-known local mysteries, abandoned places, unusual trials, and community stories with human interest.', '["abandoned town disaster","strange local trial","little-known historical mystery"]'::jsonb, 2)
   ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    query_seeds = EXCLUDED.query_seeds,
    cadence_weight = EXCLUDED.cadence_weight,
    active = true,
    updated_at = now()`,
  `INSERT INTO research_settings (key, value)
   VALUES ('autopilot', '{"enabled":true}'::jsonb)
   ON CONFLICT (key) DO NOTHING`,
  `UPDATE stories SET beat_id = '44444444-4444-4444-8444-444444444444' WHERE beat_id IS NULL`,
];
